import { StyleSheet } from "react-native";

export const layoutStyles = StyleSheet.create({
  report: { alignSelf: "center", paddingBottom: 24 },
  desktopDashboard: { width: "100%", flexDirection: "row", alignItems: "flex-start", gap: 10 },
  desktopWorkspace: { minWidth: 0, flex: 1 },
  informationRail: { width: 300, gap: 8 },
  summaryStrip: { marginBottom: 10, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderRadius: 12, flexDirection: "row", alignItems: "center", gap: 18 },
  summaryIdentity: { minWidth: 185 },
  summaryStripMobile: { flexDirection: "column", alignItems: "stretch", gap: 10 },
  summaryIdentityMobile: { minWidth: 0 },
  summaryClassification: { fontSize: 9, fontWeight: "800" },
  summaryTime: { marginTop: 3, fontSize: 8 },
  metrics: { minWidth: 0, flex: 1, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: { minWidth: 110, flex: 1 },
  metricLabel: { fontSize: 7, fontWeight: "800" },
  metricValue: { marginTop: 3, fontSize: 12, fontWeight: "800", fontVariant: ["tabular-nums"] },
  reportTabs: { marginBottom: 12, padding: 4, borderWidth: 1, borderRadius: 12, flexDirection: "row", gap: 4 },
  reportTabsMobile: { flexWrap: "wrap" },
  reportTabsVertical: { width: 130, marginBottom: 0, padding: 6, flexDirection: "column", gap: 5 },
  railHeading: { paddingHorizontal: 7, paddingTop: 7, paddingBottom: 9 },
  railEyebrow: { fontSize: 8, fontWeight: "800" },
  railTitle: { marginTop: 2, fontSize: 17, fontWeight: "800" },
  reportTab: { minWidth: 0, minHeight: 38, flex: 1, paddingHorizontal: 8, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  reportTabMobile: { flexBasis: "30%", flexGrow: 1, flexShrink: 1 },
  reportTabText: { fontSize: 9, fontWeight: "800", textTransform: "uppercase" },
  reportTabVertical: { minHeight: 62, flex: 0, paddingHorizontal: 8, flexDirection: "column", alignItems: "flex-start", justifyContent: "center", gap: 5 },
  reportTabTextVertical: { fontSize: 9.5, lineHeight: 13, textAlign: "left" },
  mapSurface: { width: "100%" },
  mapHeading: { marginBottom: 8, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 10 },
  mapHeadingCopy: { minWidth: 0, flex: 1 },
  mapTitle: { fontSize: 18, fontWeight: "800" },
  mapMeta: { marginTop: 2, fontSize: 8, fontWeight: "600" },
  liveBadge: { paddingHorizontal: 7, paddingVertical: 4, borderWidth: 1, borderRadius: 999 },
  liveBadgeText: { fontSize: 7, fontWeight: "800" },
  empty: { alignSelf: "center", padding: 20, borderWidth: 1, borderRadius: 14 },
  emptyTitle: { fontSize: 16, fontWeight: "800" },
  emptyText: { marginTop: 6, fontSize: 10, lineHeight: 16 },
});
