import { StyleSheet } from "react-native";

export const panelStyles = StyleSheet.create({
  conditionsCard: { padding: 14, borderWidth: 1, borderRadius: 12 },
  conditionsHeading: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  conditionsEyebrow: { fontSize: 9, fontWeight: "800" },
  conditionsLabel: { marginTop: 3, fontSize: 8.5, fontWeight: "700" },
  liveDot: { width: 8, height: 8, borderRadius: 4 },
  primaryWind: { marginTop: 9, flexDirection: "row", alignItems: "flex-end", gap: 7 },
  primaryWindValue: { fontSize: 38, lineHeight: 40, fontWeight: "800", fontVariant: ["tabular-nums"] },
  primaryWindUnit: { fontSize: 14, fontWeight: "800" },
  primaryWindMeta: { marginTop: 1, fontSize: 9, fontWeight: "800" },
  conditionsMetrics: { marginTop: 9, flexDirection: "row", flexWrap: "wrap", gap: 7 },
  railMetric: { minWidth: 105, flex: 1 },
  railMetricWide: { minWidth: "100%" },
  railMetricLabel: { fontSize: 8, fontWeight: "800" },
  railMetricValue: { marginTop: 3, fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
  conditionsUpdated: { marginTop: 11, paddingTop: 9, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#303A46", fontSize: 8, fontWeight: "700" },
  forecastRail: { padding: 12, borderWidth: 1, borderRadius: 12 },
  forecastRailHeading: { marginBottom: 4, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  forecastRailTitle: { fontSize: 16, fontWeight: "800" },
  forecastRailMeta: { marginTop: 3, fontSize: 8, fontWeight: "700" },
  advisoryBadge: { fontSize: 9, fontWeight: "800" },
  forecastRailList: { width: "100%" },
  forecastRailRow: { minHeight: 51, paddingVertical: 7, flexDirection: "row", alignItems: "center", gap: 7 },
  forecastRailTime: { minWidth: 0, flex: 1 },
  forecastRailTimeText: { fontSize: 10, fontWeight: "800" },
  forecastRailPosition: { marginTop: 3, fontSize: 8, fontWeight: "700" },
  forecastStrengthBadge: { maxWidth: 120, minWidth: 108, paddingHorizontal: 7, paddingVertical: 6, borderWidth: 1, borderRadius: 6 },
  forecastStrengthBadgeText: { fontSize: 8.5, fontWeight: "800", textAlign: "center" },
  sectionHeading: { marginTop: 18, marginBottom: 8, flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: 10 },
  sectionTitle: { fontSize: 16, fontWeight: "800" },
  sectionMeta: { minWidth: 0, flexShrink: 1, fontSize: 8, fontWeight: "700", textAlign: "right", textTransform: "uppercase" },
  summaryGrid: { gap: 7 },
  statusCard: { minHeight: 58, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  statusCopy: { minWidth: 0, flex: 1 },
  statusTitle: { fontSize: 11, fontWeight: "800" },
  statusText: { marginTop: 3, fontSize: 8, lineHeight: 12 },
  nextForecast: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  nextPoint: { minWidth: 155, flex: 1, paddingHorizontal: 9, paddingVertical: 8, borderWidth: 1, borderRadius: 9 },
  nextTime: { fontSize: 8, fontWeight: "800" },
  nextStrength: { marginTop: 3, fontSize: 9, fontWeight: "800" },
  nextPosition: { marginTop: 2, fontSize: 7, fontWeight: "700" },
  modelControls: { marginTop: 9, gap: 6 },
  modelControlsCompact: { marginTop: 6 },
  modelViewRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  smallTag: { minHeight: 27, paddingHorizontal: 10, borderWidth: 1, borderRadius: 999, justifyContent: "center" },
  smallTagText: { fontSize: 8, fontWeight: "800", textTransform: "uppercase" },
  aidRow: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  aidTag: { minHeight: 25, paddingHorizontal: 7, borderWidth: 1, borderRadius: 7, flexDirection: "row", alignItems: "center", gap: 5 },
  aidLine: { width: 12, height: 3, borderRadius: 2 },
  aidTagText: { fontSize: 7.5, fontWeight: "800" },
  agreement: { marginTop: 8, minHeight: 42, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderRadius: 9, flexDirection: "row", alignItems: "center", gap: 12 },
  agreementTitle: { fontSize: 10, fontWeight: "800" },
  agreementValue: { fontSize: 8, fontWeight: "800", fontVariant: ["tabular-nums"] },
  agreementNote: { minWidth: 0, flex: 1, fontSize: 7, textAlign: "right" },
  guidanceGrid: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  guidanceRow: { minHeight: 39, paddingHorizontal: 7, paddingVertical: 6, borderWidth: 1, borderRadius: 9, flexDirection: "row", alignItems: "center", gap: 7 },
  guidanceColor: { width: 3, height: 22, borderRadius: 2 },
  guidanceAid: { minWidth: 40, color: "#FFFFFF", paddingHorizontal: 5, paddingVertical: 4, borderRadius: 5, backgroundColor: "#007C91", fontSize: 8, fontWeight: "800", textAlign: "center" },
  guidanceName: { minWidth: 0, flex: 1, fontSize: 10, fontWeight: "800" },
  guidanceStat: { fontSize: 7.5, fontWeight: "700", fontVariant: ["tabular-nums"] },
  alertStatus: { minHeight: 62, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  productGrid: { marginTop: 8, flexDirection: "row", flexWrap: "wrap", gap: 7 },
  product: { minHeight: 52, paddingHorizontal: 10, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 8 },
  productCopy: { minWidth: 0, flex: 1 },
  productTitle: { fontSize: 10, fontWeight: "800" },
  productText: { marginTop: 2, fontSize: 8 },
  locationNotice: { marginTop: 10, padding: 12, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  prepareButton: { marginTop: 10, minHeight: 44, borderRadius: 9, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  prepareButtonText: { color: "#003638", fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
  disclaimer: { marginTop: 14, fontSize: 9, lineHeight: 14 },
});
