import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { alignSelf: "center", paddingBottom: 24 },
  progressCard: { marginBottom: 10, padding: 14, borderWidth: 1, borderRadius: 14, flexDirection: "row", alignItems: "center", gap: 14 },
  progressRing: { width: 64, height: 64, borderWidth: 6, borderRadius: 32, alignItems: "center", justifyContent: "center" },
  percent: { fontSize: 14, fontWeight: "800" },
  progressCopy: { minWidth: 0, flex: 1 },
  ready: { fontSize: 16, fontWeight: "800" },
  finish: { marginTop: 4, fontSize: 10, lineHeight: 14 },
  progressActions: { alignItems: "flex-end" },
  sectionProgress: { fontSize: 18, fontWeight: "800", fontVariant: ["tabular-nums"] },
  sectionProgressLabel: { marginTop: 2, fontSize: 7, fontWeight: "800" },
  workspace: { gap: 10 },
  workspaceDesktop: { flexDirection: "row", alignItems: "flex-start" },
  sectionNav: { padding: 5, borderWidth: 1, borderRadius: 12, flexDirection: "row", flexWrap: "wrap", gap: 5 },
  sectionNavDesktop: { width: 220, flexDirection: "column", flexWrap: "nowrap" },
  sectionTab: { minWidth: 150, minHeight: 48, flex: 1, paddingHorizontal: 10, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTabDesktop: { minWidth: 0, minHeight: 72, flex: 0 },
  sectionTabCopy: { minWidth: 0, flex: 1 },
  sectionTabTitle: { fontSize: 11, fontWeight: "800" },
  sectionTabDescription: { marginTop: 3, fontSize: 8, lineHeight: 11 },
  sectionTabCount: { fontSize: 8, fontWeight: "800" },
  sectionContent: { minWidth: 0, flex: 1 },
  sectionHeading: { minHeight: 54, marginBottom: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  sectionHeadingMobile: { alignItems: "flex-start", flexDirection: "column" },
  sectionHeadingCopy: { minWidth: 0, flex: 1 },
  sectionTitle: { fontSize: 20, fontWeight: "800" },
  sectionDescription: { marginTop: 3, fontSize: 10 },
  completeButton: { minHeight: 36, paddingHorizontal: 10, borderWidth: 1, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 6 },
  completeButtonText: { fontSize: 8, fontWeight: "800", textTransform: "uppercase" },
  groupGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  checkGroup: { borderWidth: 1, borderRadius: 12, overflow: "hidden" },
  checkGroupHeading: { minHeight: 43, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  checkGroupTitle: { fontSize: 12, fontWeight: "800" },
  checkGroupCount: { fontSize: 9, fontWeight: "800" },
  checkRow: { minHeight: 54, paddingHorizontal: 11, paddingVertical: 9, flexDirection: "row", alignItems: "center", gap: 10 },
  checkCircle: { width: 24, height: 24, borderWidth: 2, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  checkCopy: { minWidth: 0, flex: 1 },
  checkText: { fontSize: 11, lineHeight: 15, fontWeight: "700" },
  checkDetail: { marginTop: 3, fontSize: 8, lineHeight: 12 },
  checkedText: { textDecorationLine: "line-through" },
  planFields: { marginBottom: 10, padding: 12, borderWidth: 1, borderRadius: 12 },
  fieldsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  field: { minWidth: 190, flex: 1 },
  fieldLabel: { marginBottom: 5, fontSize: 9, fontWeight: "800" },
  fieldInput: { minHeight: 42, paddingHorizontal: 10, borderWidth: 1, borderRadius: 8, fontSize: 11 },
  saveRow: { marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  saveMessage: { minWidth: 0, flex: 1, fontSize: 8, fontWeight: "700" },
  saveButton: { minHeight: 38, paddingHorizontal: 11, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 6 },
  saveButtonText: { color: "#003638", fontSize: 9, fontWeight: "800" },
  customComposer: { padding: 14, borderWidth: 1, borderRadius: 12 },
  composerTitle: { fontSize: 14, fontWeight: "800" },
  composerText: { marginTop: 5, fontSize: 9, lineHeight: 14 },
  composerRow: { marginTop: 11, flexDirection: "row", gap: 8 },
  composerInput: { minWidth: 0, minHeight: 44, flex: 1, paddingHorizontal: 11, borderWidth: 1, borderRadius: 8, fontSize: 11 },
  addButton: { minWidth: 82, minHeight: 44, paddingHorizontal: 12, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4 },
  addButtonText: { color: "#003638", fontSize: 10, fontWeight: "800" },
  customList: { marginTop: 10, gap: 7 },
  emptyList: { padding: 24, borderWidth: 1, borderRadius: 12, alignItems: "center" },
  emptyTitle: { marginTop: 8, fontSize: 14, fontWeight: "800" },
  emptyText: { marginTop: 5, fontSize: 9, textAlign: "center" },
  safetyNote: { marginTop: 12, padding: 12, borderWidth: 1, borderRadius: 10, flexDirection: "row", alignItems: "center", gap: 9 },
  safetyNoteText: { minWidth: 0, flex: 1, fontSize: 9, lineHeight: 14 },
});
