import { StyleSheet } from "react-native";

export const nativeStyles = StyleSheet.create({
  container: { width: "100%", height: 184, overflow: "hidden", borderRadius: 13, backgroundColor: "#9CC6DD" },
  map: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  layerControl: { position: "absolute", top: 8, right: 8, flexDirection: "row", padding: 3, borderRadius: 9, backgroundColor: "rgba(5, 22, 32, .88)" },
  layerButton: { minHeight: 28, justifyContent: "center", borderRadius: 6, paddingHorizontal: 9 },
  layerButtonActive: { backgroundColor: "#FFFFFF" },
  layerText: { color: "#C9D8DE", fontSize: 9, fontWeight: "800" },
  layerTextActive: { color: "#102E3A" },
  radarCoverageNotice: { position: "absolute", top: 50, left: 12, right: 12, alignItems: "center", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: "rgba(72, 45, 4, .9)" },
  radarCoverageTitle: { color: "#FFD166", fontSize: 9, fontWeight: "900", letterSpacing: 0.4 },
  radarCoverageTitleActive: { color: "#7CF4FF" },
  radarCoverageBody: { marginTop: 2, color: "#FFFFFF", fontSize: 8, fontWeight: "700", textAlign: "center" },
  forecastCard: { position: "absolute", top: 48, right: 8, width: 188, borderRadius: 9, padding: 3, backgroundColor: "rgba(5, 22, 32, .9)" },
  forecastCardHeader: { flexDirection: "row", alignItems: "center" },
  forecastCardBody: { alignItems: "center", paddingHorizontal: 8, paddingTop: 3, paddingBottom: 5 },
  forecastCardStrength: { color: "#FFFFFF", fontSize: 10, fontWeight: "900", textAlign: "center" },
  forecastCardPosition: { marginTop: 2, color: "#BFD0D7", fontSize: 8, fontWeight: "700", textAlign: "center" },
  windTimeButton: { width: 28, height: 28, alignItems: "center", justifyContent: "center", borderRadius: 6, backgroundColor: "#FFFFFF" },
  windTimeButtonDisabled: { opacity: 0.35 },
  windTimeButtonText: { color: "#102E3A", fontSize: 18, fontWeight: "900", lineHeight: 20 },
  windTimeReadout: { minWidth: 108, alignItems: "center", paddingHorizontal: 7 },
  windTimeLabel: { color: "#FFFFFF", fontSize: 8, fontWeight: "900" },
  windLegend: { position: "absolute", left: 8, right: 8, bottom: 34, flexDirection: "row", justifyContent: "space-between", gap: 8, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 6, backgroundColor: "rgba(5, 22, 32, .9)" },
  windLegendItem: { minWidth: 0, flexDirection: "row", alignItems: "center", gap: 5 },
  windLegendSwatch: { width: 9, height: 9, borderRadius: 5 },
  windLegendSpeed: { color: "#FFFFFF", fontSize: 7, fontWeight: "900" },
  windLegendForce: { marginTop: 1, color: "#BFD0D7", fontSize: 6.5, fontWeight: "700" },
  windCenterDot: { width: 9, height: 9, borderWidth: 2, borderColor: "#07131A", borderRadius: 5, backgroundColor: "#FFFFFF" },
  forecastDot: { width: 9, height: 9, borderWidth: 1.5, borderColor: "#07131A", borderRadius: 5 },
  forecastDotSelected: { width: 12, height: 12, borderWidth: 2.5, borderRadius: 6 },
  forecastCalloutStack: { width: 96, alignItems: "center" },
  forecastCallout: { width: 96, minHeight: 42, justifyContent: "center", borderWidth: 1, borderLeftWidth: 3, borderColor: "rgba(255, 255, 255, .38)", borderRadius: 7, paddingHorizontal: 6, paddingVertical: 5, backgroundColor: "rgba(5, 22, 32, .94)" },
  forecastCalloutSelected: { borderTopColor: "#FFFFFF", borderRightColor: "#FFFFFF", borderBottomColor: "#FFFFFF" },
  forecastCalloutTime: { color: "#BCD0D8", fontSize: 7, fontWeight: "800" },
  forecastCalloutStrength: { marginTop: 2, color: "#FFFFFF", fontSize: 8, fontWeight: "900" },
  sourceBadge: { position: "absolute", left: 8, bottom: 8, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, backgroundColor: "rgba(5, 22, 32, .86)" },
  sourceText: { color: "#FFFFFF", fontSize: 8, fontWeight: "800", letterSpacing: 0.3 },
  sourceTextWarning: { color: "#FFD166" },
});
